name: stylecast
description: AI-powered outfit recommendations based on weather & your wardrobe.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  sizer: ^3.1.3
  camera: ^0.11.3
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^9.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  path: ^1.9.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/